# Programming Exercises - Chapter 10

**Stijn Lievens and Simon De Gheselle**  
June 26, 2026

This notebook contains the exercises from *Programming Exercises Chapter 10*. The text has been divided into coherent sections, and the supplied examples have been placed in code cells.


In [82]:
import keras

## Contents

1. [Classification of the Iris Dataset with an MLP](#1-classification-of-the-iris-dataset-with-an-mlp)
2. [Binary Classification with an MLP](#2-binary-classification-with-an-mlp)
3. [MNIST with a Deep MLP](#3-mnist-with-a-deep-mlp)
4. [Predicting Wine Quality with a Deep MLP](#4-predicting-wine-quality-with-a-deep-mlp)


# 1. Classification of the Iris Dataset with an MLP

In this exercise, we will build a small, very simple MLP to classify irises into 3 different species based on 4 measurements. We will keep this exercise very simple. Some things do not represent best practices.


## 1.1 Load the Data

The Iris dataset is built into `sklearn.datasets`. We use `return_X_y=True` to get a NumPy array with the features and a NumPy array with the targets.

Check the shape of these arrays. They should be `(150, 4)` and `(150,)`.


In [83]:
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)

print(X.shape, y.shape)
print(X)


(150, 4) (150,)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1

## 1.2 Build an MLP

We want to build an MLP consisting of:

- An input layer with the correct number of neurons. The name of the layer is `input`. How many neurons do we need in the input layer? 
*-> as many neurons as features of the input data. this means 4 in this case*
- One hidden layer with 5 neurons using the ReLU activation function. The name of the layer is `hidden`.
- One output layer with the correct number of neurons and the correct activation function for a classification problem. The name of the layer is `output`.


### Steps

1. Take a look at the examples in the [Keras Sequential model documentation](https://keras.io/api/models/sequential/).
2. See the [Keras activation documentation](https://keras.io/api/layers/activations/) for an example of passing an activation function via its string identifier.
3. Write similar code to create the model.
4. It is often convenient to recreate a model using a small function named `get_model`. Rewrite the previous code as a function `get_model` that returns the model described above. See the [Sequential class example](https://keras.io/api/models/model/#with-the-sequential-class).
5. Create the model using `get_model`.
6. Use the model's `summary` method to verify that the model has 43 parameters.
7. Convince yourself that you understand where this number comes from. Making a simple sketch of the model can be useful.


In [84]:
import keras

def get_model():
  model = keras.Sequential()
  model.add(keras.Input(shape=(4,), name="input"))
  model.add(keras.layers.Dense(5,activation="relu",name="hidden"))
  model.add(keras.layers.Dense(3,activation="softmax", name="output"))
  return model

model = get_model()
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ hidden (Dense)                  │ (None, 5)              │            25 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 3)              │            18 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 43 (172.00 B)

 Trainable params: 43 (172.00 B)

 Non-trainable params: 0 (0.00 B)

## 1.3 Compile the Model

Compile the model with the following options. See the [Keras model training API](https://keras.io/api/models/model_training_apis/).

- Use stochastic gradient descent with all default parameters as the optimizer.
- Specify the correct loss for a multi-class classification problem in which each instance belongs to exactly one class. Take into account that the targets have shape `(150,)`.
- Track the accuracy metric.


In [85]:
model.compile(
  optimizer="sgd",
  loss=keras.losses.sparse_categorical_crossentropy,
  metrics=("accuracy",)
)

## 1.4 Train the Model

Train the model for 20 epochs. Because we have such a small dataset, use a batch size of 8 so that there is a reasonable number of updates per epoch.

> **Note:** Since we are not using validation data, we have no way of knowing whether the model is overfitting. Do not do this in practice.


In [86]:
model.fit(
  x=X,
  y=y,
  batch_size=8,
  epochs=20
)


Epoch 1/20
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.4600 - loss: 0.9679
Epoch 2/20
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.5867 - loss: 0.8824
Epoch 3/20
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5933 - loss: 0.8388 
Epoch 4/20
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6000 - loss: 0.8104
Epoch 5/20
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.6467 - loss: 0.7595
Epoch 6/20
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.6200 - loss: 0.7271
Epoch 7/20
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.6067 - loss: 0.6908
Epoch 8/20
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.5733 - loss: 0.6578
Epoch 9/20
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.5333 - loss: 0.6262
Epoch 10/20
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.6667 - loss: 0.5949
Epoch 11/20
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7133 - loss: 0.5672
Epoch 12/20
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step 

## 1.5 Emulate the Calculations of the Model

This step is not necessary in practice. It is included here to give you a better understanding of what is going on.

First, compute the result of the model (the MLP) on a small batch.

1. Create a tensor called `X_batch` that consists of the first two training examples. Use the slice operator. What is the shape of this tensor?
   
   `(2,4)`
2. Call the model with `X_batch` as the input. Call the result `y_batch_pred`. What is the shape of this tensor? What does each dimension mean?
   
   `(2, 3). two rows, one for each data point. three columns, one for each possible outcome.`
3. Use a function from `keras.ops` to verify that the sum of each row equals one.


In [93]:
# Compute the model output for the first two training examples
X_batch = X[:2]

y_batch_pred = model(X_batch)
print(y_batch_pred)
print("\n")
print(keras.ops.sum(y_batch_pred, axis=1))

tf.Tensor(
[[0.959141   0.03424629 0.00661261]
 [0.9347809  0.05316875 0.01205031]], shape=(2, 3), dtype=float32)


tf.Tensor([0.9999999 1.       ], shape=(2,), dtype=float32)


### Reproduce the Calculations by Hand

Now emulate these calculations "by hand" and verify that you get the same results.

1. Extract the weights of the hidden layer and store them as `W1` and `b1`.


In [97]:
# Assume "model" is the name assigned to the MLP
W1, b1 = model.get_layer("hidden").get_weights()

print(
  "hidden layer:\n",
  W1.shape,
  b1.shape,
  "\n"
)

z1 = keras.ops.matmul(X_batch, W1) + b1
a1 = keras.ops.relu(z1)
print(a1, "\n")


W2, b2 = model.get_layer("output").get_weights()
print(
  "output layer:\n",
  W2.shape,
  b2.shape,
  "\n"
)

z2 = keras.ops.matmul(a1, W2) + b2
a2 = keras.ops.softmax(z2)
print(a2)



hidden layer:
 (4, 5) (5,) 

tf.Tensor(
[[3.50201676 2.31997035 0.         3.73506068 0.        ]
 [3.16819074 2.01327931 0.         3.34246259 0.        ]], shape=(2, 5), dtype=float64) 

output layer:
 (5, 3) (3,) 

tf.Tensor(
[[0.95914108 0.0342463  0.00661261]
 [0.93478092 0.05316876 0.01205032]], shape=(2, 3), dtype=float64)


2. Do the same for the weights of the output layer.
3. Verify the shape of these four tensors. Make sure that you understand them.
4. Complete the following code using only methods from `keras.ops`.


5. These are the calculations performed by the MLP. Print the shapes of `X_batch`, `a1`, and `y_batch_pred_2`, and compare them with the results shown by the model's `summary()` method.
6. Verify that `y_batch_pred` and `y_batch_pred_2` are identical by displaying both.
7. Can you combine two methods from `keras.ops` to check whether all elements of the two tensors are close to one another?


In [ ]:
# Compare the two sets of predictions
y_batch_pred_2 = a2
print(keras.ops.isclose(a2, y_batch_pred))

tf.Tensor(
[[ True  True  True]
 [ True  True  True]], shape=(2, 3), dtype=bool)


# 2. Binary Classification with an MLP

In this exercise, we are going to classify preprocessed movie reviews as either positive or negative. We will use the built-in IMDB (Internet Movie Database) Keras dataset.


## 2.1 Load the Data

1. Use `keras.datasets.imdb.load_data()` to download the IMDB dataset.
2. Limit the vocabulary to the 10,000 most frequent words by using the `num_words` argument. See the [Keras IMDB dataset documentation](https://keras.io/api/datasets/imdb/).


In [91]:
(train_data, train_labels), (test_data, test_labels) = ...  # Your code here


TypeError: cannot unpack non-iterable ellipsis object

3. Check that both `train_data` and `test_data` contain 25,000 examples.
4. Print the features of the first training example. You should see something like `[1, 14, 22, 16, ..., 178, 32]`.
5. Each example is a list of integers. You can use the function below to convert such a list back into English text. This lets you get a feel for the review, but this is not what we will feed into the neural network.


In [ ]:
def convert_to_english(list_of_integers):
    word_index = keras.datasets.imdb.get_word_index()
    # Reverse the word index
    rv_word_index = {idx: word for (word, idx) in word_index.items()}
    # Map each integer to a word and join all words together.
    # Indices 0, 1, and 2 are reserved for padding, start of sequence, and unknown.
    return " ".join(rv_word_index.get(idx - 3, "?") for idx in list_of_integers)


In [ ]:
# Inspect the dataset and convert an example to English


## 2.2 Convert the Data

It is not very convenient for a neural network to ingest lists of integers. Instead, we will use multi-hot encoding to convert the lists of integers into vectors of zeros and ones.

1. Write a function `convert_to_multi_hot(sequences, dimension)` that takes a NumPy array of sequences (lists of integers) and returns a NumPy array of shape `(len(sequences), dimension)`. Each row should be a multi-hot encoded vector of length `dimension`. You can write this function using ordinary loops. Later, we will see how to make this type of function more efficient.


In [ ]:
def convert_to_multi_hot(sequences, dimension):
    # Create a NumPy array of the correct shape and data type, filled with zeros.
    output = np.zeros(
        shape=(sequences.shape[0], dimension),
        dtype=np.float32,
    )

    # Your code here

    return output


2. Convert the training and test data to multi-hot encoded vectors. Use a dimension of 10,000 because we used 10,000 words.


In [ ]:
X_train = convert_to_multi_hot(train_data, dimension=10_000)
X_test = convert_to_multi_hot(test_data, dimension=10_000)

# Rename the labels
y_train = train_labels
y_test = test_labels


3. We also need validation data. Use the first 10,000 examples from the test data as validation data. The final 15,000 examples will be used as test data. Write code to create the validation and test data.


In [ ]:
X_val = ...   # Your code here
y_val = ...   # Your code here
X_test = ...  # Your code here
y_test = ...  # Your code here


4. **Optional:** Rewrite `convert_to_multi_hot` using only methods from `keras.ops`, such as `keras.ops.scatter_update`.


In [ ]:
# Optional: rewrite convert_to_multi_hot with keras.ops


## 2.3 Build a Model

1. Build a model using the Sequential API with the following architecture:

   - Use the `Input` function or object to indicate the shape, excluding the batch dimension, and optionally the data type of the input tensors.
   - A `Dense` layer with 16 units and the ReLU activation function.
   - A `Dense` layer with 16 units and the ReLU activation function.
   - A `Dense` output layer.

     - How many units should the output layer have?
     - What is the most appropriate activation function, given that we are doing binary classification?

2. Write a function `get_model()` that returns this model. Display the summary of the returned model. You should see that it has 160,305 trainable parameters.


In [ ]:
# Build the binary-classification model and define get_model()


## 2.4 Compile the Model

Compile the model with the following settings:

- Use `rmsprop` as the optimizer with all default parameter settings.
- Specify the correct loss for a binary classification problem.
- Track the accuracy metric.


In [ ]:
# Compile the model


## 2.5 Train the Model

1. Train the model for 20 epochs with a batch size of 512. Be sure to use the validation data.
2. Use the `history` object returned by the `fit` method to plot the learning curves. You can use the function below.
3. You should notice that the model is overfitting.
4. Initialize and compile the model again, but train for fewer epochs so that the model does not overfit.


In [ ]:
def plot_learning_curves(history):
    plt.figure(figsize=(8, 5))
    for key, style in zip(history.history, ["r-o", "r-*", "b-o", "b-*"]):
        epochs = np.array(history.epoch)
        plt.plot(epochs + 1, history.history[key], style, label=key)

    plt.xlabel("Epoch")
    plt.axis([1, len(history.history["loss"]), 0.0, 1.0])
    plt.legend(loc="lower left")
    plt.grid()


In [ ]:
# Train the model, plot the learning curves, and retrain for fewer epochs


## 2.6 Evaluate the Model

1. Use the `evaluate` method to evaluate the model on the test set.
2. What is the model's performance on the test set?

> You should get around 89% accuracy on the test set.


In [ ]:
# Evaluate the model on the test set


# 3. MNIST with a Deep MLP

This exercise is based on exercise 10 from Chapter 10 of *Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow* by Aurélien Géron. It contains more detailed instructions.


## 3.1 Load and Preprocess the MNIST Dataset

1. Use `keras.datasets.mnist.load_data()` to download the MNIST dataset.
2. Use the final 10,000 images of the training set as the validation set. This gives you 50,000 training images, 10,000 validation images, and 10,000 test images.
3. The pixel values are stored as integers from 0 to 255. Convert them to floats between 0.0 and 1.0 by dividing by 255.
4. Reshape the tensors so that they have rank 2 instead of rank 3.


In [ ]:
# Load and preprocess the MNIST dataset


## 3.2 Build an MLP

1. Use the Sequential API to build a model with two hidden layers and one output layer.
2. Use the ReLU activation function for the hidden layers, with 300 and 100 units respectively. Choose the appropriate activation function and number of units for the output layer, given that this is a multi-class classification problem.
3. Create a function `get_model()` that returns this model.
4. The model should have 266,610 parameters when you display its summary.


In [ ]:
# Build the MNIST model and define get_model()


## 3.3 Compile the Model

1. Create an SGD optimizer with a learning rate of 0.01.
2. Compile the model using the appropriate loss function for multi-class classification, taking into account that the labels are not one-hot encoded. Track the accuracy metric.


In [ ]:
# Create the optimizer and compile the model


## 3.4 Train the Model

1. Use a batch size of 256.
2. Train the model for a large number of epochs, but use the `EarlyStopping` callback to stop training when the validation accuracy has not improved for 5 epochs.
3. Also use the `ModelCheckpoint` callback to save the model with the best validation loss.
4. Use the `TensorBoard` callback to log the training process.


In [ ]:
# Configure callbacks and train the model


## 3.5 Evaluate the Model

1. Use the `evaluate` method to evaluate the model on the training, validation, and test sets.
2. Check that some of these results correspond to the output shown during training.


In [ ]:
# Evaluate the model on the training, validation, and test sets


## 3.6 Try Different Learning Rates and Batch Sizes

1. Try different learning rates, for example `[0.01, 0.05, 0.1, 0.5]`, and batch sizes, for example `[64, 128, 256, 512]`. Observe how they affect the model's performance.
2. Check the learning curves in TensorBoard to inspect how training progressed.
3. Save all the different models and try to find the best one. Evaluate its performance on the test set.


In [ ]:
# Run experiments with different learning rates and batch sizes


# 4. Predicting Wine Quality with a Deep MLP

In this exercise, we build a deep MLP to predict wine quality. We will treat this as a regression problem.


## 4.1 Load the Data

1. Download the [Wine Quality dataset](https://archive.ics.uci.edu/dataset/186/wine+quality) using `keras.utils.get_file()`.
2. Load `winequality-white.csv` into a Pandas DataFrame. We will use the 11 features to predict wine quality, which we view as a real number.
3. What is the distribution of the target variable?
4. Create the tensor of features $X$ and the tensor of targets $y$.
5. Use 20% of the complete dataset as the test set. Use `train_test_split` from scikit-learn.
6. Use 20% of the remaining data as the validation set. Again use `train_test_split`.
7. What are the shapes of the training, validation, and test sets?


In [ ]:
# Download, load, inspect, and split the wine-quality data


## 4.2 Build an MLP

1. Define a `Normalization` layer that ensures that the mean and standard deviation of each feature are close to zero and one, respectively.
2. Adapt this layer only on the training data to prevent data leakage.
3. Use the Sequential API to build a model that starts with the normalization layer, followed by three hidden layers and one output layer. Use the ReLU activation function for the hidden layers, with 50 units each. Choose the appropriate activation function and number of units for the output layer, given that this is a regression problem.
4. Create a function `get_model(normalization_layer)` that returns this model. Note that the normalization layer is passed as an argument.
5. Display the summary of the returned model. It should have 5,774 parameters in total, of which 23 are non-trainable.
6. Make sure that you understand where these numbers come from.


In [ ]:
# Define and adapt the normalization layer, then build the model


## 4.3 Compile the Model

1. Create an Adam optimizer with a learning rate of $1/1000$.
2. Compile the model using mean absolute error as the loss function.


In [ ]:
# Create the optimizer and compile the model


## 4.4 Train the Model

1. Train the model for 20 epochs using a batch size of 32.
2. Use the `history` object returned by the `fit()` method to plot the learning curves. Is the model overfitting?


In [ ]:
# Train the model and plot the learning curves


## 4.5 Evaluate the Model

1. Use the `evaluate()` method to evaluate the model on the test set.
2. What is the mean absolute error on the test set?
3. Calculate the mean absolute error for each of the different wine quality values in the test set. Does the model perform differently depending on the quality of the wine?


In [ ]:
# Evaluate the model and calculate the error for each wine quality
